# Generated by Django 3.0.8 on 2020-08-19 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('image_path', models.ImageField(upload_to='img')),
                ('image_icon_path', models.ImageField(default=None, upload_to='img')),
                ('max_level', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TownResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.IntegerField()),
                ('wine', models.IntegerField()),
                ('marble', models.IntegerField()),
                ('crystal', models.IntegerField()),
                ('sulfur', models.IntegerField()),
                ('wood_production', models.IntegerField(default=0)),
                ('wine_production', models.IntegerField(default=0)),
                ('marble_production', models.IntegerField(default=0)),
                ('crystal_production', models.IntegerField(default=0)),
                ('sulfur_production', models.IntegerField(default=0)),
                ('tavern_expenses', models.IntegerField(default=0)),
                ('save_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Town')),
            ],
        ),
        migrations.AddField(
            model_name='town',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.User'),
        ),
        migrations.CreateModel(
            name='BuildingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('is_upgraded', models.BooleanField(default=False)),
                ('building_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Town')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Building')),
            ],
        ),
    ]
