# Generated by Django 3.0.8 on 2020-08-19 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townresources',
            name='save_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 10, 9, 23, 55, 59, 342380)),
        ),
    ]
