# Generated by Django 3.0.8 on 2020-08-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_path', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='UnitInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Town')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Unit')),
            ],
        ),
    ]
