# Generated by Django 3.0.8 on 2020-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_unit_unitinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='hour_costs',
            field=models.IntegerField(default=0),
        ),
    ]
