# Generated by Django 3.0.8 on 2020-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_auto_20200827_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='town',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
