# Generated by Django 3.0.8 on 2020-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20200828_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='economy_future',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='military_future',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='science_future',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_future',
            field=models.IntegerField(default=0),
        ),
    ]
