# Generated by Django 3.0.8 on 2020-08-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_auto_20200829_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unit',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
