# Generated by Django 3.0.8 on 2020-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20200829_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='mine_image_path',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
