# Generated by Django 3.0.8 on 2020-09-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_resource_mine_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='x',
        ),
        migrations.RemoveField(
            model_name='town',
            name='y',
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('wood_level', models.IntegerField(default=0)),
                ('luxury_level', models.IntegerField(default=0)),
                ('luxury_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury_resource_fk', to='helper.Resource')),
                ('wood_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wood_resource_fk', to='helper.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='town',
            name='island',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.Island'),
        ),
    ]
