# Generated by Django 3.0.8 on 2020-09-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_auto_20200902_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miracle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_path', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='island',
            name='miracle_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='island',
            name='luxury_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luxury_resource_fk', to='helper.Resource'),
        ),
        migrations.AddField(
            model_name='island',
            name='miracle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.Miracle'),
        ),
    ]
