# Generated by Django 3.0.8 on 2020-09-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0013_auto_20200902_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building_levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='defensive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='generals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='master_builders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='offensive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='piracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='research_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='resources',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='scientists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trading',
            field=models.IntegerField(default=0),
        ),
    ]
