# Generated by Django 3.0.8 on 2020-09-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_auto_20200903_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alliance',
            field=models.CharField(default='', max_length=50),
        ),
    ]
