# Generated by Django 3.0.8 on 2020-09-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0015_user_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='in_game_id',
            field=models.IntegerField(default=0),
        ),
    ]
