# Generated by Django 3.0.8 on 2020-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0016_town_in_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='name',
            field=models.CharField(default='Brak', max_length=50),
        ),
    ]
