# Generated by Django 3.0.8 on 2020-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0017_island_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
