# Generated by Django 3.0.8 on 2020-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0018_island_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ammunition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='armor_upgrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='barracks_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='crystal_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='hit_points_upgrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='men_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='sulfur_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='wine_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='wood_costs',
            field=models.IntegerField(default=0),
        ),
    ]
