# Generated by Django 3.0.8 on 2020-10-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0019_auto_20201002_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='big_image_path',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
