# Generated by Django 3.0.8 on 2020-10-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0020_unit_big_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='hit_points_upgrade',
            new_name='damage_upgrade',
        ),
    ]
