# Generated by Django 3.0.8 on 2020-10-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0021_auto_20201002_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('level', models.IntegerField(default=0)),
                ('progress', models.CharField(max_length=100)),
                ('image_path', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Achievement')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.AchievementCategory'),
        ),
    ]
