# Generated by Django 3.0.8 on 2020-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0022_auto_20201003_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementlevel',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
