# Generated by Django 3.0.8 on 2020-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0023_achievementlevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='max_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='progress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
