# Generated by Django 3.0.8 on 2020-10-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0024_auto_20201008_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementlevel',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
