# Generated by Django 3.0.8 on 2020-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0025_auto_20201022_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ammunition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='armor_upgrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='big_image_path',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='ship',
            name='crystal_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='damage_upgrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='men_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='shipyard_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='sulfur_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='wine_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='wood_costs',
            field=models.IntegerField(default=0),
        ),
    ]
