# Generated by Django 3.0.8 on 2020-11-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0026_auto_20201028_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('workers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SawMillWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('workers', models.IntegerField(default=0)),
            ],
        ),
    ]
