# Generated by Django 3.0.8 on 2020-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0027_mineworkers_sawmillworkers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineworkers',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sawmillworkers',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
