# Generated by Django 3.0.8 on 2020-11-02 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0028_auto_20201101_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2015, 10, 9, 23, 55, 59, 342380)),
        ),
    ]
