# Generated by Django 3.0.2 on 2021-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0029_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='no_ships',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='town',
            name='no_units',
            field=models.BooleanField(default=False),
        ),
    ]
