# Generated by Django 3.0.2 on 2021-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0030_auto_20210710_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='has_tower',
            field=models.BooleanField(default=False),
        ),
    ]
