# Generated by Django 3.0.8 on 2021-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0031_island_has_tower'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status_name', models.CharField(max_length=40)),
            ],
        ),
    ]
