# Generated by Django 3.0.8 on 2021-07-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0033_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alliance',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
