# Generated by Django 3.0.2 on 2021-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0034_auto_20210713_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
            ],
        ),
    ]
