# Generated by Django 3.2.5 on 2021-07-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0035_registerkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.BigIntegerField(default=0),
        ),
    ]
