from django.db import connection
from django.contrib.auth.decorators import login_required
from ..models import User

from django.shortcuts import get_object_or_404, render


@login_required(login_url='helper:login')
def get_resources_rank(request, user_id):
    order = request.GET.get('order', 'wood')
    user = get_object_or_404(User, pk=user_id)
    user.save()

    resources_by_user = get_resources_by_user(order)[:50]
    context = {
        'user': user,
        'user_id': user_id,
        'resources_by_user': resources_by_user,
        'order': order,
        'title': 'Ranking surowców'
    }
    return render(request, 'helper/resources_rank.html', context)


def get_resources_by_user(order):
    cursor = connection.cursor()
    if order == 'wood':
        cursor.execute(
            "SELECT u.id, u.user_name, SUM(s.workers) as myorder, SUM(m.workers), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 2 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 3 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 4 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 5 AND user.id = u.id) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as u ON t.user_id = u.id GROUP BY u.id ORDER BY myorder DESC")
    elif order == 'luxury':
        cursor.execute(
            "SELECT u.id, u.user_name, SUM(s.workers), SUM(m.workers) as myorder, (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 2 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 3 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 4 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 5 AND user.id = u.id) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as u ON t.user_id = u.id GROUP BY u.id ORDER BY myorder DESC")
    elif order == 'wine':
        cursor.execute(
            "SELECT u.id, u.user_name, SUM(s.workers), SUM(m.workers), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 2 AND user.id = u.id) as myorder, (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 3 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 4 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 5 AND user.id = u.id) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as u ON t.user_id = u.id GROUP BY u.id ORDER BY myorder DESC")
    elif order == 'marble':
        cursor.execute(
            "SELECT u.id, u.user_name, SUM(s.workers), SUM(m.workers), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 2 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 3 AND user.id = u.id) as myorder, (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 4 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 5 AND user.id = u.id) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as u ON t.user_id = u.id GROUP BY u.id ORDER BY myorder DESC")
    elif order == 'crystal':
        cursor.execute(
            "SELECT u.id, u.user_name, SUM(s.workers), SUM(m.workers), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 2 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 3 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 4 AND user.id = u.id) as myorder, (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 5 AND user.id = u.id) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as u ON t.user_id = u.id GROUP BY u.id ORDER BY myorder DESC")
    elif order == 'sulfur':
        cursor.execute(
            "SELECT u.id, u.user_name, SUM(s.workers), SUM(m.workers), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 2 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 3 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 4 AND user.id = u.id), (SELECT SUM(m.workers) FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as user ON t.user_id = u.id WHERE i.luxury_resource_id = 5 AND user.id = u.id) as myorder FROM helper_sawmillworkers AS s INNER JOIN helper_island as i ON i.wood_level = s.level INNER JOIN helper_mineworkers as m ON i.luxury_level = m.level INNER JOIN helper_town as t ON t.island_id = i.id INNER JOIN helper_user as u ON t.user_id = u.id GROUP BY u.id ORDER BY myorder DESC")
    results = cursor.fetchall()
    return results
